### ISSUE TITLE
Setting Endpoint activation or expiration date results in invalid Peppol SMP response

### ISSUE THREAD

**Issue by sfieten** [holodeck-b2b/Holodeck-SMP#5]
When either the Activation or Expiration date is set the Peppol `ServiceMetadata` response is invalid as the respective elements are empty.

**Comment by mirvnillith** [comment]
This sounds major and would not allow Holodeck to be used in a real SMP scenario? I.e. it would not allow Peppol IDs to join and/or leave the SMP as their businesses migrate to and from an access point.
